### ISSUE TITLE
Copy and paste from clipboard

### ISSUE THREAD

**Issue by gBopHuk** [equalsraf/vim-qt#5]
How to copy and paste from clipboard? In gvim  and vim it feature provided by SHIFT/CTRL+insert.
But in vim-qt I get \<S-Insert\> or \<C-Insert\> text in the buffer.

**Comment by 10110111** [comment]
Normally in gVim you'll also get `<S-Insert>` and `<C-Insert>` (unless you have special keybindings for this). In Vim you have it work because the terminal emulator you use supports this. In X11 gVim the correct way is `"+y` to yank and `"+P` to paste.

**Comment by gBopHuk** [comment]
All maps I have
<pre>
$ grep map ~/.gvimrc
"nmap <F9> :NERDTreeToggle<CR>
:map <F5> :setlocal spell! spelllang=ru<CR>
":map <t_%9> :AirlineRefresh <CR>
:map <C-F9> :AirlineRefresh <CR>

$ grep map ~/.vimrc
"leader map 
let mapleader = ","
map <leader><ESC> :nohl<CR>
imap [ []<LEFT>
imap ( ()<LEFT>
imap { {}<LEFT>
"inoremap \" \""<LEFT>
"inoremap ' ''<LEFT>
let g:ctrlp_map = '<c-p>'
nmap <F9> :NERDTreeToggle<CR>
nmap <S-F9> :NERDTreeFromBookmark
" Plugin key-mappings.
"imap <TAB>     <Plug>(neosnippet_expand_or_jump)
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
"imap <expr><TAB>
"smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	nmap <F3> :q<CR>
:map <c-F12> :AirlineRefresh <CR>
</pre>

Which of them provide that behavior?

**Comment by gBopHuk** [comment]
I add to the ~/.gvimrc
<pre> 
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
</pre>
And I got  past to the buffer from clipboard. But in gvim that works without that hack.
